#ifndef GGCMI_WTH_GEN_TESTS_LOCATION_TEST_H_
#define GGCMI_WTH_GEN_TESTS_LOCATION_TEST_H_
#define GNV_GRID_LON 29.25
#define GNV_GRID_LAT -82.75
#define C_GRID_LON -0.25
#define C_GRID_LAT 0.25
#endif //GGCMI_WTH_GEN_TESTS_LOCATION_TEST_H_
